/**
 * Superintendências Regionais e Unidades Prisionais da Polícia Penal de
 * Santa Catarina. Dados portados do PAD V1 (github.com/SEPEN-DPP/PAD,
 * data/unidades.json) em 2026-07-14 — mesmo conteúdo institucional, sem
 * nenhuma lógica do V1 reaproveitada. Nomes de diretor/superintendente e
 * contatos mudam com o tempo; ver ROADMAP.md quanto a migrar isto para uma
 * coleção editável do Firestore quando a Fase 1/2 tiver uma tela de gestão.
 */

/** Superintendências Regionais, indexadas pelo código (ex.: 'SR01'). */
export const SUPERINTENDENCIAS_REGIONAIS = Object.freeze({
  SR01: { nome: 'Superintendência Regional da Grande Florianópolis', superintendente: 'Kelvyn Diehl', email: 'sr01@pp.sc.gov.br', telefone: '(48) 3665‑9131' },
  SR02: { nome: 'Superintendência Regional Sul', superintendente: 'Marcos Aurélio Spinardi', email: 'sr02@pp.sc.gov.br', telefone: '(48) 3403‑1501' },
  SR03: { nome: 'Superintendência Regional do Norte Catarinense', superintendente: 'Efraym Ben José Falcão', email: 'sr03@pp.sc.gov.br', telefone: '(47) 3481‑3993' },
  SR04: { nome: 'Superintendência Regional do Vale do Itajaí', superintendente: 'Anderson Luiz Teodoro', email: 'sr04@pp.sc.gov.br', telefone: '(47) 3398‑6704' },
  SR05: { nome: 'Superintendência Regional Serrana', superintendente: 'Fabiano Deitos Rech', email: 'sr05@pp.sc.gov.br', telefone: '(49) 3412‑3300' },
  SR06: { nome: 'Superintendência Regional Oeste', superintendente: 'Guimorvan Boita', email: 'sr06@pp.sc.gov.br', telefone: '(49) 2049‑9768' },
  SR07: { nome: 'Superintendência Regional do Médio Vale do Itajaí', superintendente: 'Ricardo da Silva Morlo', email: 'sr07@pp.sc.gov.br', telefone: '(47) 3378‑8594' },
  SR08: { nome: 'Superintendência Regional do Planalto Norte', superintendente: 'Edenilson Schelbauer', email: 'sr08@pp.sc.gov.br', telefone: '(47) 3647‑0229' },
});

/** Unidades prisionais do Estado. */
export const UNIDADES_PRISIONAIS = Object.freeze([
  { nome: 'Penitenciária de Florianópolis', cidade: 'Florianópolis', superintendencia: 'SR01', diretor: 'Max Cleber Orth', email: 'pe01@pp.sc.gov.br', telefone: '(48) 3665‑9123', endereco: 'Rua Delminda da Silveira, 960 – Agronômica – Florianópolis/SC – CEP 88025‑500' },
  { nome: 'Complexo Penitenciário do Estado', cidade: 'São Pedro de Alcântara', superintendencia: 'SR01', diretor: 'Flávio Brasil Ganciné', email: 'pe02@pp.sc.gov.br', telefone: '(48) 3664‑2750', endereco: 'Rua Adriano Enning, s/n – Bairro Santa Tereza – São Pedro de Alcântara/SC – CEP 88125‑000' },
  { nome: 'Presídio Regional de Tijucas', cidade: 'Tijucas', superintendencia: 'SR01', diretor: 'Nathasha Daberkow Vieira', email: 'pr03@pp.sc.gov.br', telefone: '(48) 3665‑9280', endereco: 'Rua Alberto Tomazi, s/n – Bairro Itinga – Tijucas/SC – CEP 88200‑000' },
  { nome: 'Hospital de Custódia e Tratamento Psiquiátrico – HCTP', cidade: 'Florianópolis', superintendencia: 'SR01', diretor: 'Fábio Medeiros Wiese', email: 'hctp@pp.sc.gov.br', telefone: '(48) 3665‑9191', endereco: 'Rua Delminda da Silveira, s/n – Agronômica – Florianópolis/SC – CEP 88025‑500' },
  { nome: 'Presídio Regional de Biguaçu', cidade: 'Biguaçu', superintendencia: 'SR01', diretor: 'Fabiano Oliveira Suares', email: 'pr04@pp.sc.gov.br', telefone: '(48) 3664‑2700', endereco: 'Rua Hermógenes Prazeres, 49 – Centro – Biguaçu/SC – CEP 88160‑152' },
  { nome: 'Presídio Masculino Regional de Florianópolis', cidade: 'Florianópolis', superintendencia: 'SR01', diretor: 'Joana Mahfuz Vicini', email: 'pr01@pp.sc.gov.br', telefone: '(48) 3665‑9256', endereco: 'Rua Delminda da Silveira, 900 – Agronômica – Florianópolis/SC – CEP 88025‑500' },
  { nome: 'Presídio Feminino Regional de Florianópolis', cidade: 'Florianópolis', superintendencia: 'SR01', diretor: 'Marina Pamplona Coelho', email: 'pr02@pp.sc.gov.br', telefone: '(48) 3665‑9107', endereco: 'Rua Lauro Linhares, s/n – Trindade – Florianópolis/SC – CEP 88036‑001' },
  { nome: 'Unidade de Monitoramento Eletrônico', cidade: 'Florianópolis', superintendencia: 'SR01', diretor: 'Gustavo Costa Vieira', email: 'ume@pp.sc.gov.br', telefone: '(48) 3665‑7327', endereco: 'Rua Fúlvio Aducci, 1214 – Estreito – Florianópolis/SC' },
  { nome: 'Colônia Agroindustrial de Palhoça', cidade: 'Palhoça', superintendencia: 'SR01', diretor: 'Renata de Souza de Oliveira', email: 'cogri@pp.sc.gov.br', telefone: '(48) 3664‑5580', endereco: 'Rua José João Barcelos, s/n – Bela Vista – Palhoça/SC – CEP 88132‑770' },
  { nome: 'Penitenciária Feminina de Criciúma', cidade: 'Criciúma', superintendencia: 'SR02', diretor: 'Virginia Gabriela Gonzales', email: 'pe04@pp.sc.gov.br', telefone: '(48) 3403‑1737', endereco: 'Rua José Marinho Teixeira, s/n – São Domingos – Criciúma/SC – CEP 88812‑680' },
  { nome: 'Penitenciária Masculina de Tubarão', cidade: 'Tubarão', superintendencia: 'SR02', diretor: 'Deiveison Querino Batista', email: 'pe05@pp.sc.gov.br', telefone: '(48) 3631‑9777', endereco: 'Rua Maria Menegaz, 735 – São João – Tubarão/SC – CEP 88708‑570' },
  { nome: 'Penitenciária Sul', cidade: 'Criciúma', superintendencia: 'SR02', diretor: 'Juliana Borges Medeiros', email: 'pe03@pp.sc.gov.br', telefone: '(48) 3403‑1485', endereco: 'Rua José Marinho Teixeira, 5005 – São Domingos – Criciúma/SC – CEP 88812‑680' },
  { nome: 'Presídio Regional de Araranguá', cidade: 'Araranguá', superintendencia: 'SR02', diretor: 'Daniel Possamai Vieira', email: 'pr08@pp.sc.gov.br', telefone: '(48) 3529‑0441', endereco: 'Rua Renato Carbonera, 500 – Araranguá/SC – CEP 88900‑000' },
  { nome: 'Presídio Regional de Criciúma', cidade: 'Criciúma', superintendencia: 'SR02', diretor: 'Júnior Rodrigo Fagundes', email: 'pr05@pp.sc.gov.br', telefone: '(48) 3403‑1516', endereco: 'Rua Odonel Bianchi, 330 – Santa Augusta – Criciúma/SC – CEP 88805‑265' },
  { nome: 'Presídio Regional de Imbituba', cidade: 'Imbituba', superintendencia: 'SR02', diretor: 'Filipe Gonzaga Lopes', email: 'pr09@pp.sc.gov.br', telefone: '(48) 3647‑7409', endereco: 'Rua 13 de Setembro, s/n – Vila Nova Alvorada – Imbituba/SC – CEP 88780‑000' },
  { nome: 'Presídio Regional de Laguna', cidade: 'Laguna', superintendencia: 'SR02', diretor: 'Rafael Nunes de Oliveira', email: 'pr10@pp.sc.gov.br', telefone: '(48) 3647‑7425', endereco: 'Rua Idelfonso Batista, s/n – Progresso – Laguna/SC – CEP 88790‑000' },
  { nome: 'Presídio Regional de Tubarão', cidade: 'Tubarão', superintendencia: 'SR02', diretor: 'Gladson Antônio da Silva', email: 'pr06@pp.sc.gov.br', telefone: '(48) 3631‑9780', endereco: 'Rua Maria Menegaz, 635 – São João – Tubarão/SC – CEP 88708‑570' },
  { nome: 'Penitenciária Industrial de Joinville', cidade: 'Joinville', superintendencia: 'SR03', diretor: 'Márcio Simbalista', email: 'pe06@pp.sc.gov.br', telefone: '(47) 3481‑3948', endereco: 'Servidão Antônio Deglmann Júnior, 245 – Parque Guarani – Joinville/SC – CEP 89209‑240' },
  { nome: 'Presídio Feminino Regional de Joinville', cidade: 'Joinville', superintendencia: 'SR03', diretor: 'Eliana Eloi', email: 'pr12@pp.sc.gov.br', telefone: '(47) 3481‑2369', endereco: 'Servidão Antônio Deglmann Júnior, 245 – Parque Guarani – Joinville/SC – CEP 89209‑240' },
  { nome: 'Presídio Regional de Joinville', cidade: 'Joinville', superintendencia: 'SR03', diretor: 'André Felippe Dias', email: 'pr11@pp.sc.gov.br', telefone: '(47) 3481‑3900', endereco: 'Servidão Antônio Deglmann Júnior, 245 – Parque Guarani – Joinville/SC – CEP 89209‑240' },
  { nome: 'Presídio Regional de Barra Velha', cidade: 'Barra Velha', superintendencia: 'SR03', diretor: 'Léia Cristina Steffen Fuck', email: 'pr14@pp.sc.gov.br', telefone: '(47) 3481‑2885', endereco: 'Rua João Anselmo Breniensen, s/n – Vila Nova – Barra Velha/SC – CEP 88390‑000' },
  { nome: 'Presídio Regional de São Francisco do Sul', cidade: 'São Francisco do Sul', superintendencia: 'SR03', diretor: 'Lamartine Ximenes Fernandes', email: 'pr13@pp.sc.gov.br', telefone: '(47) 3481‑3932', endereco: 'Estrada Geral da Pedreira – Bairro Miranda – São Francisco do Sul/SC – CEP 89240‑000' },
  { nome: 'Penitenciária Masculina do Vale do Itajaí', cidade: 'Itajaí', superintendencia: 'SR04', diretor: 'Bruno Domingos Gabriel', email: 'pe07@pp.sc.gov.br', telefone: '(47) 3398‑6700', endereco: 'Estrada Geral João Tomaz Pinto, s/n – Canhanduba – Itajaí/SC – CEP 88307‑770' },
  { nome: 'Presídio Feminino Regional de Itajaí', cidade: 'Itajaí', superintendencia: 'SR04', diretor: 'Michele Rebello de Mesquita', email: 'pr16@pp.sc.gov.br', telefone: '(47) 3398‑6185', endereco: 'Estrada Geral João Tomaz Pinto, s/n – Canhanduba – Itajaí/SC – CEP 88307‑770' },
  { nome: 'Presídio Regional de Brusque', cidade: 'Brusque', superintendencia: 'SR04', diretor: 'Giovani Manfredini Queiroz', email: 'pr17@pp.sc.gov.br', telefone: '(47) 3251‑8280', endereco: 'Rod. SC‑408, km 02 – Bairro Santa Luzia – Brusque/SC – CEP 88357‑340' },
  { nome: 'Presídio Regional de Itajaí', cidade: 'Itajaí', superintendencia: 'SR04', diretor: 'Rogério José Bizatto', email: 'pr15@pp.sc.gov.br', telefone: '(47) 3398‑6750', endereco: 'Estrada Geral João Tomaz Pinto, s/n – Canhanduba – Itajaí/SC – CEP 88307‑770' },
  { nome: 'Presídio Regional de Itapema', cidade: 'Itapema', superintendencia: 'SR04', diretor: 'Eduardo Weber Xavier', email: 'pr18@pp.sc.gov.br', telefone: '(47) 3398‑6684', endereco: 'Rua 440, s/n – Bairro Morretes – Itapema/SC – CEP 88220‑000' },
  { nome: 'Penitenciária Industrial de São Cristóvão do Sul', cidade: 'São Cristóvão do Sul', superintendencia: 'SR05', diretor: 'Giselle Cordeiro Demeneck Remor', email: 'pe09@pp.sc.gov.br', telefone: '(49) 3412‑3190', endereco: 'Estrada Geral Paredão, s/n – São Cristóvão do Sul/SC – CEP 89533‑000' },
  { nome: 'Penitenciária Regional de Curitibanos', cidade: 'São Cristóvão do Sul', superintendencia: 'SR05', diretor: 'Fabio Marcelo Palhano', email: 'pe08@pp.sc.gov.br', telefone: '(49) 3412‑3300', endereco: 'Rua Juventino França de Moraes, s/n – São Cristóvão do Sul/SC – CEP 89533‑000' },
  { nome: 'Presídio Masculino de Lages', cidade: 'Lages', superintendencia: 'SR05', diretor: 'Rodrigo Araújo Aquino', email: 'pr19@pp.sc.gov.br', telefone: '(49) 3289‑8467', endereco: 'Rua Ricardo Marin, s/n – Bairro Santa Clara – Lages/SC – CEP 88513‑210' },
  { nome: 'Presídio Regional de Lages', cidade: 'Lages', superintendencia: 'SR05', diretor: 'Ricardo Fernando Moreira Floriani', email: 'pr20@pp.sc.gov.br', telefone: '(49) 3289‑8403', endereco: 'Rua Mato Grosso, 247 – Bairro São Cristóvão – Lages/SC – CEP 88509‑220' },
  { nome: 'Presídio Regional de Caçador', cidade: 'Caçador', superintendencia: 'SR05', diretor: 'André Luiz Pierdona', email: 'pr21@pp.sc.gov.br', telefone: '(49) 3561‑6945', endereco: 'Av. Albino Felipe Potrick, 50 – Bom Sucesso – Caçador/SC – CEP 89501‑335' },
  { nome: 'Presídio Regional de Campos Novos', cidade: 'Campos Novos', superintendencia: 'SR05', diretor: 'Evalcir Morais dos Santos', email: 'pr22@pp.sc.gov.br', telefone: '(49) 3541‑3588', endereco: 'Estrada Geral Usina Velha, s/n – Interior – Campos Novos/SC – CEP 89620‑000' },
  { nome: 'Presídio Regional de Videira', cidade: 'Videira', superintendencia: 'SR05', diretor: 'Fabio Antunes Ramos', email: 'pr23@pp.sc.gov.br', telefone: '(49) 3533‑5915', endereco: 'Rodovia SC‑303, Linha Scussiato, Interior – Videira/SC – CEP 89560‑000' },
  { nome: 'Unidade de Segurança Máxima de São Cristóvão do Sul', cidade: 'São Cristóvão do Sul', superintendencia: 'SR05', diretor: 'Daniel de Sena', email: 'umax@pp.sc.gov.br', telefone: '(49) 3412‑3241', endereco: 'Rua Juventino França de Moraes, s/n – São Cristóvão do Sul/SC – CEP 89533‑000' },
  { nome: 'Penitenciária Agrícola de Chapecó', cidade: 'Chapecó', superintendencia: 'SR06', diretor: 'Itacir Ricieri Cella', email: 'pe10@pp.sc.gov.br', telefone: '(49) 2049‑9760', endereco: 'Rua Cunha Porã, 1600‑E – Bairro Efapi – Chapecó/SC – CEP 89809‑500' },
  { nome: 'Penitenciária Industrial de Chapecó', cidade: 'Chapecó', superintendencia: 'SR06', diretor: 'Iuri Elias Berwanger', email: 'pe11@pp.sc.gov.br', telefone: '(49) 2049‑9713', endereco: 'Rua Cunha Porã, 1600‑E – Bairro Efapi – Chapecó/SC – CEP 89809‑500' },
  { nome: 'Presídio Feminino Regional de Chapecó', cidade: 'Chapecó', superintendencia: 'SR06', diretor: 'Agda Remus', email: 'pr25@pp.sc.gov.br', telefone: '(49) 2049‑9813', endereco: 'Rua Cunha Porã, 1600‑E – Bairro Efapi – Chapecó/SC – CEP 89809‑500' },
  { nome: 'Presídio Regional de Chapecó', cidade: 'Chapecó', superintendencia: 'SR06', diretor: 'José Lauri Pelizzari', email: 'pr24@pp.sc.gov.br', telefone: '(49) 2049‑9602', endereco: 'Rua Cunha Porã, 1600‑E – Bairro Efapi – Chapecó/SC – CEP 89809‑500' },
  { nome: 'Presídio Regional de Concórdia', cidade: 'Concórdia', superintendencia: 'SR06', diretor: 'Rafael Schlegel Rodrigues Salgado', email: 'pr26@pp.sc.gov.br', telefone: '(49) 3482‑6222', endereco: 'Rua Adílio Hilário Mutzemberg, s/n – Guilherme Reich – Concórdia/SC – CEP 89709‑132' },
  { nome: 'Presídio Regional de Joaçaba', cidade: 'Joaçaba', superintendencia: 'SR06', diretor: 'Liliam Wiest', email: 'pr27@pp.sc.gov.br', telefone: '(49) 3527‑9829', endereco: 'BR‑282, km 391 – Vila Remor – Joaçaba/SC – CEP 89600‑000' },
  { nome: 'Presídio Regional de Maravilha', cidade: 'Maravilha', superintendencia: 'SR06', diretor: 'Marcelo Rodrigo Langaro', email: 'pr29@pp.sc.gov.br', telefone: '(49) 3664‑6672', endereco: 'Av. Sul Brasil, 1607 – Centro – Maravilha/SC – CEP 89874‑000' },
  { nome: 'Presídio Regional de São José do Cedro', cidade: 'São José do Cedro', superintendencia: 'SR06', diretor: 'Rejane Birci Schrader de Mattos', email: 'pr30@pp.sc.gov.br', telefone: '(49) 3644‑3436', endereco: 'Rua Amambuy esq. Dom Pedro, 673 – Jardim – São José do Cedro/SC – CEP 89930‑000' },
  { nome: 'Presídio Regional de São Miguel do Oeste', cidade: 'São Miguel do Oeste', superintendencia: 'SR06', diretor: 'Eduardo Francisco Bregola Junior', email: 'pr31@pp.sc.gov.br', telefone: '(49) 3631‑3754', endereco: 'Rua Oiapoc, 1795 – Centro – São Miguel do Oeste/SC – CEP 89900‑000' },
  { nome: 'Presídio Regional de Xanxerê', cidade: 'Xanxerê', superintendencia: 'SR06', diretor: 'Vitor Matte', email: 'pr28@pp.sc.gov.br', telefone: '(49) 3382‑2269', endereco: 'Rua Maranhão, 1780 – Castelo Branco – Xanxerê/SC – CEP 89820‑000' },
  { nome: 'Penitenciária Industrial de Blumenau', cidade: 'Blumenau', superintendencia: 'SR07', diretor: 'Luciano Cardoso', email: 'pe12@pp.sc.gov.br', telefone: '(47) 3378‑8600', endereco: 'Rua Silvano Candido da Silva, 4601 – Ponta Aguda – Blumenau/SC – CEP 89050‑287' },
  { nome: 'Presídio Regional de Blumenau', cidade: 'Blumenau', superintendencia: 'SR07', diretor: 'Augusto Gregory Hilgenberg Ijaille', email: 'pr32@pp.sc.gov.br', telefone: '(47) 3378‑8716', endereco: 'Rua General Osório, 4585 – Passo Manso – Blumenau/SC – CEP 89032‑239' },
  { nome: 'Presídio Regional de Indaial', cidade: 'Indaial', superintendencia: 'SR07', diretor: 'Ivã Carlos Fuck', email: 'pr34@pp.sc.gov.br', telefone: '(47) 3399‑3193', endereco: 'Rua Otto Stange, 127 – Bairro Estados – Indaial/SC – CEP 89086‑045' },
  { nome: 'Presídio Regional de Ituporanga', cidade: 'Ituporanga', superintendencia: 'SR07', diretor: 'Marisoni dos Santos', email: 'pr35@pp.sc.gov.br', telefone: '(47) 3533‑8797', endereco: 'Rua Governador Jorge Lacerda, 72 – Centro – Ituporanga/SC – CEP 88400‑000' },
  { nome: 'Presídio Regional de Rio do Sul', cidade: 'Rio do Sul', superintendencia: 'SR07', diretor: 'Victor Hugo Vanelli', email: 'pr33@pp.sc.gov.br', telefone: '(47) 3526‑3308', endereco: 'Estrada Geral Serra Canoas, s/n – Fundo Canoas – Rio do Sul/SC' },
  { nome: 'Penitenciária Industrial de São Bento do Sul', cidade: 'São Bento do Sul', superintendencia: 'SR08', diretor: 'Leó Da Silva Feliciano', email: 'pe13@pp.sc.gov.br', telefone: '(47) 3647‑0240', endereco: 'Rua Miguel Hubl, 400 – Lençol – São Bento do Sul/SC – CEP 89289‑580' },
  { nome: 'Presídio Regional de Canoinhas', cidade: 'Canoinhas', superintendencia: 'SR08', diretor: 'Alexander Marcelo Costa', email: 'pr38@pp.sc.gov.br', telefone: '(47) 3627‑4352', endereco: 'Rua Catarina de Souza Hubner, 1035 – Bairro Piedade – Canoinhas/SC – CEP 89460‑613' },
  { nome: 'Presídio Regional de Jaraguá do Sul', cidade: 'Jaraguá do Sul', superintendencia: 'SR08', diretor: 'Carlos de Almeida Rossato', email: 'pr36@pp.sc.gov.br', telefone: '(47) 3276‑9409', endereco: 'Rua Alvino Flor da Silva, 901 – Jaraguá do Sul/SC – CEP 89260‑875' },
  { nome: 'Presídio Regional de Mafra', cidade: 'Mafra', superintendencia: 'SR08', diretor: 'Gabriel Henning', email: 'pr37@pp.sc.gov.br', telefone: '(47) 3647‑0222', endereco: 'Rua Getúlio Vargas, 604 – Centro – Mafra/SC – CEP 89300‑210' },
  { nome: 'Presídio Regional de Porto União', cidade: 'Porto União', superintendencia: 'SR08', diretor: 'Josmar Mattos e Santos', email: 'pr39@pp.sc.gov.br', telefone: '(47) 3627‑4340', endereco: 'Rua Matos Costa, 772 – Centro – Porto União/SC – CEP 89400‑000' },
]);

/** Busca uma unidade pelo nome exato (usado para popular selects/formulários). */
export function obterUnidadePorNome(nome) {
  return UNIDADES_PRISIONAIS.find((u) => u.nome === nome) ?? null;
}
